### PR TITLE
Create seagrass.png.mcmeta

### PR DESCRIPTION
**Pull request by broes5**
Adding this fixes the broken sea grass texture.

### CODE REVIEW

**Comment by broes5** [comment]
Why are these files even missing in this branch? They're there in the branch for 1.19.2, but not 1.16.5.

**Comment by 3vorp** [comment]
because only 1.19 is actively supported, any other versions are just what the bot has been pushing without any actual maintenance

**Comment by broes5** [comment]
Could I maintain this branch? I've noticed other things wrong since noticing the broken kelp and sea grass textures. I'd like to fix them.

**Comment by HARYA301** [comment]
> Could I maintain this branch? I've noticed other things wrong since noticing the broken kelp and sea grass textures. I'd like to fix them.

Hi!
I have fixed bugs with .mcmeta in 1.12, 1.13, 1.14, 1.15, 1.16 and 1.17. None of them issue should occure anymore.

**Comment by broes5** [comment]
Great! I guess there's no point in these pull requests existing anymore.

**Pull request closed without merging**
